# permissions for end users to view databasereadonlyreplicas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: databasereadonlyreplica-viewer-role
rules:
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databasereadonlyreplicas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - databases.digitalocean.com
  resources:
  - databasereadonlyreplicas/status
  verbs:
  - get
